class LanguageNames {
  static final Map<String, String> languageNames = {
    'mai-IN': 'Maithili (India)',
    'hr-HR': 'Croatian (Croatia)',
    'ko-KR': 'Korean (South Korea)',
    'mr-IN': 'Marathi (India)',
    'as-IN': 'Assamese (India)',
    'ru-RU': 'Russian (Russia)',
    'zh-TW': 'Chinese (Taiwan)',
    'hu-HU': 'Hungarian (Hungary)',
    'sw-KE': 'Swahili (Kenya)',
    'sd-IN': 'Sindhi (India)',
    'ks-IN': 'Kashmiri (India)',
    'th-TH': 'Thai (Thailand)',
    'doi-IN': 'Dogri (India)',
    'ur-PK': 'Urdu (Pakistan)',
    'nb-NO': 'Norwegian Bokmål (Norway)',
    'da-DK': 'Danish (Denmark)',
    'tr-TR': 'Turkish (Turkey)',
    'et-EE': 'Estonian (Estonia)',
    'pt-PT': 'Portuguese (Portugal)',
    'vi-VN': 'Vietnamese (Vietnam)',
    'en-US': 'English (US)',
    'ur-IN': 'Urdu (India)',
    'sat-IN': 'Santali (India)',
    'sq-AL': 'Albanian (Albania)',
    'sv-SE': 'Swedish (Sweden)',
    'ar': 'Arabic',
    'su-ID': 'Sundanese (Indonesia)',
    'sr-RS': 'Serbian (Serbia)',
    'bn-BD': 'Bengali (Bangladesh)',
    'bs-BA': 'Bosnian (Bosnia and Herzegovina)',
    'mni-IN': 'Manipuri (India)',
    'gu-IN': 'Gujarati (India)',
    'kn-IN': 'Kannada (India)',
    'el-GR': 'Greek (Greece)',
    'hi-IN': 'Hindi (India)',
    'fi-FI': 'Finnish (Finland)',
    'bn-IN': 'Bengali (India)',
    'km-KH': 'Khmer (Cambodia)',
    'fr-FR': 'French (France)',
    'id-ID': 'Indonesian (Indonesia)',
    'uk-UA': 'Ukrainian (Ukraine)',
    'pa-IN': 'Punjabi (India)',
    'en-AU': 'English (Australia)',
    'nl-NL': 'Dutch (Netherlands)',
    'fr-CA': 'French (Canada)',
    'lv-LV': 'Latvian (Latvia)',
    'he-IL': 'Hebrew (Israel)',
    'pt-BR': 'Portuguese (Brazil)',
    'de-DE': 'German (Germany)',
    'ml-IN': 'Malayalam (India)',
    'si-LK': 'Sinhala (Sri Lanka)',
    'cs-CZ': 'Czech (Czech Republic)',
    'is-IS': 'Icelandic (Iceland)',
    'pl-PL': 'Polish (Poland)',
    'ca-ES': 'Catalan (Spain)',
    'sk-SK': 'Slovak (Slovakia)',
    'it-IT': 'Italian (Italy)',
    'fil-PH': 'Filipino (Philippines)',
    'lt-LT': 'Lithuanian (Lithuania)',
    'ne-NP': 'Nepali (Nepal)',
    'ms-MY': 'Malay (Malaysia)',
    'en-NG': 'English (Nigeria)',
    'nl-BE': 'Dutch (Belgium)',
    'zh-CN': 'Chinese (China)',
    'es-ES': 'Spanish (Spain)',
    'ja-JP': 'Japanese (Japan)',
    'ta-IN': 'Tamil (India)',
    'bg-BG': 'Bulgarian (Bulgaria)',
    'cy-GB': 'Welsh (UK)',
    'or-IN': 'Odia (India)',
    'brx-IN': 'Bodo (India)',
    'sa-IN': 'Sanskrit (India)',
    'yue-HK': 'Cantonese (Hong Kong)',
    'en-IN': 'English (India)',
    'es-US': 'Spanish (US)',
    'kok-IN': 'Konkani (India)',
    'jv-ID': 'Javanese (Indonesia)',
    'sl-SI': 'Slovenian (Slovenia)',
    'te-IN': 'Telugu (India)',
    'ro-RO': 'Romanian (Romania)',
    'en-GB': 'English (UK)',
  };
}
